### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lifeiscontent** [benawad/destiny#120]
log:

```
> npx destiny -w "src/**/*.*"
INFO: Generating tree for: src/**/*.*
(node:46825) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at isTestFile (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:489:57)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:590:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
    at fn (/Users/lifeiscontent/.npm/_npx/46825/lib/node_modules/destiny/lib/destiny.js:627:9)
(node:46825) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:46825) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by benawad** [comment]
is it possible to share the repo you ran this on?

**Comment by lifeiscontent** [comment]
@benawad i don’t think so, but I don’t mind doing a pair programming session to let you debug if that works for you.

**Comment by benawad** [comment]
that works, I'll shoot you an email

**Comment by lifeiscontent** [comment]
@benawad sorry for the late response, I have responded to the email.
