### ISSUE TITLE
Tests are failing in Windows

### ISSUE THREAD

**Issue by roguib** [benawad/destiny#157]
I was playing around with the project, trying to find an optimal solution for https://github.com/benawad/destiny/issues/142 since I'm on Windows, but after making some changes to the codebase I decided to run the test suites with ```yarn test``` and some of them were failing. I thought that maybe was a consequence of my changes, so I tried again without any changes and tests were still failing. The results were the following:

```
Test Suites: 7 failed, 4 passed, 11 total
Tests:       46 failed, 52 passed, 98 total
Snapshots:   10 failed, 118 obsolete, 118 written, 20 passed, 148 total
Time:        69.965s
Ran all test suites
```

I'm missing some command? Let me know if you need more information 😄

**Comment by roguib** [comment]
Just a quick update. After installing node and yarn in WLS2 I was able to pass all the tests. The results were the following:

```
Test Suites: 11 passed, 11 total                                                                                        
Tests:       98 passed, 98 total                                                                                        
Snapshots:   148 passed, 148 total                                                                                      
Time:        167.841s                                                                                                   
Ran all test suites.
```

I'm not sure why tests are failing in Windows PowerShell or, at least, in my PowerShell. I'd like to use the debugger to be able to inspect the code but, for some reason, it fails after being attached with the following message.

```
Debugger attached.
Waiting for the debugger to disconnect...
C:\Users\roger\Documents\Proyectos\destiny-fork\node_modules\.bin\jest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:992:16)
    at Module._compile (internal/modules/cjs/loader.js:1040:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
I've tried to change the base directory to destiny_fork, thinking that maybe the slash was causing some problems, but the error wasn't fixed.

**Comment by Ryan-Florida** [comment]
@roguib looking at your error message, it seems that you are closing your double-quotes early.
`basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
--------------------^ ------ ^
Those two are your open and closing delimiters, hence the `missing ) after argument list` SyntaxError.

**Comment by roguib** [comment]
Yeah but I think it's something related to Jest running in Windows since the error comes from that package. I couldn't have the time to play around but maybe upgrading Jest version would be enough for fixing it.
